server:
  port: 8090
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: Mohit
    url: jdbc:oracle:thin:@localhost:1522:xe
    username: system
    
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: update
    show-sql: true
